USE [master]
GO

/****** Object:  Database [ddd]    Script Date: 29.04.2025 11:20:24 ******/
CREATE DATABASE [ddd]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ddd', FILENAME = N'D:\SQL2022\MSSQL16.MSSQLSERVER\MSSQL\DATA\ddd.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ddd_log', FILENAME = N'D:\SQL2022\MSSQL16.MSSQLSERVER\MSSQL\DATA\ddd_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ddd].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ddd] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ddd] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ddd] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ddd] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ddd] SET ARITHABORT OFF 
GO

ALTER DATABASE [ddd] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ddd] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ddd] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ddd] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ddd] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ddd] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ddd] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ddd] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ddd] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ddd] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ddd] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ddd] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ddd] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ddd] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ddd] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ddd] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ddd] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ddd] SET RECOVERY FULL 
GO

ALTER DATABASE [ddd] SET  MULTI_USER 
GO

ALTER DATABASE [ddd] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ddd] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ddd] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ddd] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ddd] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ddd] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ddd] SET QUERY_STORE = ON
GO

ALTER DATABASE [ddd] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [ddd] SET  READ_WRITE 
GO

