//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dddEntities1 : DbContext
    {
        public dddEntities1()
            : base("name=dddEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Checkers> Checkers { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Devices> Devices { get; set; }
        public virtual DbSet<Managers> Managers { get; set; }
        public virtual DbSet<Masters> Masters { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Parts_and_Materials> Parts_and_Materials { get; set; }
        public virtual DbSet<Requests> Requests { get; set; }
        public virtual DbSet<Results> Results { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
