//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parts_and_Materials
    {
        public int id { get; set; }
        public int costs { get; set; }
        public int lefted { get; set; }
        public Nullable<int> DeviceId { get; set; }
    
        public virtual Devices Devices { get; set; }
    }
}
